name = "ExpressionExplorer"
uuid = "27279169-5e6b-450a-a298-ff8b56ddcd23"
license = "MIT"
authors = ["Paul Berg <paul@plutojl.org>", "Fons van der Plas <fons@plutojl.org>", "Stephan Sahm <stephan.sahm@jolin.io>"]
version = "1.0.401"

[compat]
julia = "1.6"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Test"]
